---
title: "Training Visualization"
author: "Ben Weinstein"
date: "June 1, 2017"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2,lib.loc="C:/Users/Ben/Documents/R/win-library/3.2")
library(dplyr,lib.loc="C:/Users/Ben/Documents/R/win-library/3.2")
library(knitr,lib.loc="C:/Users/Ben/Documents/R/win-library/3.2")
library(printr,lib.loc="C:/Users/Ben/Documents/R/win-library/3.2")

opts_chunk$set(warning=F,message=F,echo=F)
```


```{r}
#get file list.
filnames<-list.files("C:/Users/Ben/Dropbox/GoogleCloud/Summary",full.names = T,pattern=".csv")
preds<-bind_rows(lapply(filnames,function(x){
  
  #read csv
  dat<-read.csv(x)
  
  #assign date
  date<-str_match(x,"DeepMeerkat_(\\w+)_(\\w+)_\\w+.csv")
  dat$date<-format(strptime(date[,2],"%Y%m%d"))
  
  #eval or holdout
  dat$type<-str_match(x,"DeepMeerkat_\\w+_\\w+_(\\w+).csv")[,2]
  return(dat)
  }))

#strip key name paths
preds$ID<-as.character(str_match(preds$key,"\\w+.jpg"))
preds$TrueLabel<-as.numeric(str_detect(preds$key,"Positives"))

#lookup label in dict
labels<-read.table("dict.txt")
preds$PredLabel<-(labels$V1[preds$prediction+1]=="positive")*1
sumtable<-preds %>% group_by(date,type,True=TrueLabel,Predicted=PredLabel) %>% summarize("%"=n()/sum(n()))
kable(sumtable)

#calculate recall
retable<-preds %>% group_by(date,type) %>% summarize(recall=sum(TrueLabel==1)/sum(PredLabel==1),accuracy=sum(TrueLabel==1&PredLabel==1)/sum(PredLabel==1))
recall<-sum((sumtable$Predicted==1))/sum((sumtable$True==1))
kable(retable)
```
